# Generated by Django 4.2.5 on 2023-09-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_support_', '0002_rename_quizquestions_quizquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='text_answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='text_question',
            new_name='question_text',
        ),
    ]
