# Generated by Django 4.2.5 on 2023-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizQuestions',
            new_name='QuizQuestion',
        ),
    ]
